steps:
- name: python
  entrypoint: pip
  args: ["install", "-r", "requirements.txt", "--user"]
- name: python
  entrypoint: pip
  args: ["-m", "build"]
- name: python
  entrypoint: python
  args:
  - '-m'
  - 'twine'
  - 'upload'
  - '--repository-url'
  - 'https://europe-west1-python.pkg.dev/lindsaysmith-convoy-playground/python-test/'
  - 'dist/*'
  